name: SonarCloud analysis

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]
  workflow_dispatch:

jobs:
  Analysis:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up JDK
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 17

      - name: Build Android project
        run: |
          cd InsecureBankv2
          chmod +x gradlew
          ./gradlew assembleDebug

      - name: Analyze with SonarCloud
        uses: SonarSource/sonarcloud-github-action@v2.2.0
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        with:
          projectBaseDir: InsecureBankv2
          args: >
            -Dsonar.projectKey=Sambit-rgb_Java-Android-InsecureBankv2
            -Dsonar.organization=sambit-rgb
            -Dsonar.sources=app/src/main/java
            -Dsonar.java.binaries=app/build/intermediates/javac/debug/classes
